image: ghcr.io/astral-sh/uv:python3.12-trixie@sha256:6fbe5da29909abd8ae455ebef9c18ae5d008788997bbf2a6d60ace0890f3905a

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - $UV_CACHE_DIR
    
before_script:
  - uv sync

ci:
  script:
    - echo "OK"
